name: ROS2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ros_distribution: [ jazzy ]

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup ROS2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.ros_distribution }}

      - name: Build Colcon Workspace
        run: |
          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
          colcon build --base-path src